
# Detect build architecture
BUILDARCH ?= $(shell uname -m)
ifeq ($(BUILDARCH),aarch64)
    BUILDARCH=arm64
endif
ifeq ($(BUILDARCH),x86_64)
    BUILDARCH=amd64
endif

ifneq ($(wildcard user.env),)
include user.env
endif

# Use containerized environment
CONTAINER?=0
CONTAINER_ENGINE ?= docker

CONTAINER_IMAGE_NAME ?= mds_builder_image
CONTAINER_TAG ?= latest
CONTAINER_COMMAND := ${CONTAINER_ENGINE} run -it --rm \
		--volume="$(CURDIR):$(CURDIR)" \
		-v mds-builder-build:$(CURDIR)/build \
		--workdir="$(CURDIR)" \
		$(CONTAINER_IMAGE_NAME):$(CONTAINER_TAG)

BUILDROOT_VERSION ?= 2026.02.1

MACHINE ?= network_player

WORKSPACE ?= $(shell pwd)
CONFIG_NAME=mds_${MACHINE}_defconfig
CONFIG_FILE?=buildroot_config/${CONFIG_NAME}
OUTPUT_DIR?=${WORKSPACE}/build/output/${MACHINE}
EXTERNAL_REPOSITORIES?=${WORKSPACE}/mds_external
BUILD_VERSION ?=  $(shell git describe --tags --dirty --always)

ifeq ($(CONTAINER), 1)
	DEPS = container-image
	PREFIX = $(CONTAINER_COMMAND)
else
	DEPS =
	PREFIX =
endif

### DEFAULT TARGET ###

build: $(DEPS) br-downloads config ## Build target.
	@echo ">>> Build target [${MACHINE}]"
	$(PREFIX) make -C ${WORKSPACE}/build/buildroot-${BUILDROOT_VERSION} BR2_EXTERNAL=$(EXTERNAL_REPOSITORIES) O=$(OUTPUT_DIR)
.PHONY: build

sdk: build ## Build target. 
	@echo ">>> Build SDK [${MACHINE}]"
	$(PREFIX) make -C ${WORKSPACE}/build/buildroot-${BUILDROOT_VERSION} BR2_EXTERNAL=$(EXTERNAL_REPOSITORIES) O=$(OUTPUT_DIR) BR2_SDK_PREFIX=sdk-mds-${MACHINE}-${BUILD_VERSION} sdk
.PHONY: build

build-%: $(DEPS) br-downloads ## Build specific package
	@echo ">>> Build package [$*] for target [${MACHINE}]"
	$(PREFIX) make -C ${WORKSPACE}/build/buildroot-${BUILDROOT_VERSION} BR2_EXTERNAL=$(EXTERNAL_REPOSITORIES) O=$(OUTPUT_DIR) $*
.PHONY: build-%

config: $(DEPS)
	$(PREFIX) cp $(CONFIG_FILE) build/buildroot-${BUILDROOT_VERSION}/configs
	$(PREFIX) make -C ${WORKSPACE}/build/buildroot-${BUILDROOT_VERSION} O=$(OUTPUT_DIR) BR2_EXTERNAL=$(EXTERNAL_REPOSITORIES) $(CONFIG_NAME)
.PHONY: config

menuconfig: $(DEPS)
	$(PREFIX) cp $(CONFIG_FILE) build/buildroot-${BUILDROOT_VERSION}/configs
	$(PREFIX) make -C ${WORKSPACE}/build/buildroot-${BUILDROOT_VERSION} O=$(OUTPUT_DIR) BR2_EXTERNAL=$(EXTERNAL_REPOSITORIES) $(CONFIG_NAME)
	$(PREFIX) make -C ${WORKSPACE}/build/buildroot-${BUILDROOT_VERSION} O=$(OUTPUT_DIR) BR2_EXTERNAL=$(EXTERNAL_REPOSITORIES) menuconfig
	$(PREFIX) make -C ${WORKSPACE}/build/buildroot-${BUILDROOT_VERSION} O=$(OUTPUT_DIR) BR2_EXTERNAL=$(EXTERNAL_REPOSITORIES) savedefconfig
	$(PREFIX) cp ${WORKSPACE}/build/buildroot-${BUILDROOT_VERSION}/configs/$(CONFIG_NAME) $(CONFIG_FILE)
.PHONY: menuconfig

# linux-menuconfig: $(DPES)
# 	make build-linux-menuconfig
# 	make build-linux-savedefconfig
# 	$(PREFIX) cp ${WORKSPACE}/build/output/network_player/build/linux-6.7.2/defconfig ${WORKSPACE}/mds_external/board/mds_network_player/kernel_defconfig

# uboot-menuconfig: $(DPES)
# 	make build-uboot-menuconfig
# 	make build-uboot-savedefconfig
# 	$(PREFIX) cp build/output/network_player/build/uboot-2024.04-rc1/defconfig mds_external/board/mds_network_player/u-boot_defconfig

clean-all: ## Clean output repository. It will wipe out all the intermediary files generated by buildroot
	rm -rf "${WORKSPACE}/build/output"
.PHONY: clean-all

clean: ## Clean output repository of the current MACHINE. It will wipe out all the intermediary files generated by buildroot
	rm -rf "$(OUTPUT_DIR)"
.PHONY: clean

###Distribution rules ###
DESTDIR?=${WORKSPACE}/build/distribution/${MACHINE}

${DESTDIR}:
	mkdir -p ${DESTDIR}

.PHONY: distrib

distrib-clean: ## Remove the distribution directory
	rm -rf ${DESTDIR}

### DOWNLOAD Buildroot ###
build/.stamp-br-downloads:
	@echo ">>> Download buildroot source code"
	$(PREFIX) mkdir -p build
	git clone https://gitlab.com/buildroot.org/buildroot.git build/buildroot-${BUILDROOT_VERSION}
	git -C build/buildroot-${BUILDROOT_VERSION} checkout ${BUILDROOT_VERSION}
	### $(PREFIX) curl -s https://buildroot.org/downloads/buildroot-${BUILDROOT_VERSION}.tar.gz | tar xz -C build/
	touch build/.stamp-br-downloads

br-downloads: build/.stamp-br-downloads ## Download buildroot source code
.PHONY: br-downloads

### bootstrap ###
bootstrap: ## Run the bootstrap + NAND provisioning (pass SERIAL=/dev/ttyUSB0 to monitor)
	./bootstrap.sh $(SERIAL)
.PHONY: bootstrap

### bootstrap self-extracting bundle (makeself) ###
BUNDLE_NAME ?= bootstrap-$(BUILD_VERSION).run
BUNDLE_STAGING := $(WORKSPACE)/build/bootstrap-bundle
BOOTSTRAP_OUT := $(WORKSPACE)/out/network_player_bootstrap
PROD_OUT := $(WORKSPACE)/out/network_player

bootstrap-bundle: ## Build a self-extracting .run that bootstraps + provisions a board
	@command -v makeself >/dev/null 2>&1 || { \
		echo "ERROR: makeself not found. Install it (e.g. apt install makeself)." >&2; exit 1; }
	@echo ">>> Building bootstrap artifacts"
	$(MAKE) build MACHINE=network_player_bootstrap
	@echo ">>> Building production artifacts"
	$(MAKE) build MACHINE=network_player
	@echo ">>> Staging bundle in $(BUNDLE_STAGING)"
	rm -rf "$(BUNDLE_STAGING)"
	mkdir -p "$(BUNDLE_STAGING)"
	install -m 0755 bootstrap.sh "$(BUNDLE_STAGING)/bootstrap.sh"
	cp "$(BOOTSTRAP_OUT)/u-boot-sunxi-with-spl.bin" "$(BUNDLE_STAGING)/"
	cp "$(BOOTSTRAP_OUT)/uImage" "$(BUNDLE_STAGING)/"
	cp "$(BOOTSTRAP_OUT)/rootfs.cpio.uboot" "$(BUNDLE_STAGING)/"
	cp "$(BOOTSTRAP_OUT)/suniv-f1c200s-mds-network-streamer-v1.0.dtb" "$(BUNDLE_STAGING)/"
	cp "$(PROD_OUT)/spi-nand.bin" "$(BUNDLE_STAGING)/"
	cp "$(PROD_OUT)/rootfs.ubifs" "$(BUNDLE_STAGING)/"
	@echo ">>> Packing $(BUNDLE_NAME)"
	makeself "$(BUNDLE_STAGING)" "$(WORKSPACE)/$(BUNDLE_NAME)" \
		"MDS Network Player bootstrap $(BUILD_VERSION)" ./bootstrap.sh
	@echo ">>> Bundle ready: $(WORKSPACE)/$(BUNDLE_NAME)"
	@echo ">>> Run it with: ./$(BUNDLE_NAME) -- /dev/ttyUSB0"
.PHONY: bootstrap-bundle

### CONTAINER RULES ###

container-image: Dockerfile ## Build Docker image
	@${CONTAINER_ENGINE} build \
		--ssh=default \
		--build-arg="USER_UID=$(shell id -u)" \
		--build-arg="USER_GID=$(shell id -g)" \
		--build-arg="PROJECT_PATH=$(CURDIR)" \
		--tag=$(CONTAINER_IMAGE_NAME):$(CONTAINER_TAG) \
		.
.PHONY: container-image

containter-shell: container-image ## Run shell in container
	@$(CONTAINER_COMMAND) /bin/bash
.PHONY: container-shell

container-rm: ## Remove Docker image
	@${CONTAINER_ENGINE} image rm $(CONTAINER_IMAGE_NAME):$(CONTAINER_TAG)
.PHONY: container-rm

### SUPPORT RULES ###
help:           ## Show this help.
	@awk 'BEGIN {FS = ":.*##"; printf "Usage: make \033[36m<target>\033[0m\n"} /^[a-zA-Z_-]+:.*?##/ { printf "\033[36m%-30s\033[0m %s\n", $$1, $$2 } /^##@/ { printf "\n\033[1m%s\033[0m\n", substr($$0, 5) } ' $(MAKEFILE_LIST)
.PHONY: help

.DEFAULT_GOAL := help
