base_url = "https://naguirre.github.io/mds-builder"
title = "Manufacture du Son"
description = "Documentation for the Manufacture du Son network audio player"
theme = "mds"

build_search_index = true
default_language = "en"
generate_feeds = true
generate_sitemap = true

[markdown]
bottom_footnotes = true

[markdown.highlighting]
enabled = true
theme = "github-dark"

[extra]
github_repo = "naguirre/mds-builder"
github_branch = "main"
